### ISSUE TITLE
Missing Content, required restart

### ISSUE THREAD

**Issue by kennyparsons** [debridmediamanager/zurg-testing#13] opened 2023-12-06 22:58 UTC
I use a combination of RDTClient, Zurg, rclone-rd, and Debrid Media Manager. RDT is not really in use, but it's hooked up to my account. I mainly use DMM and rclone-rd for production, and zurg is just for testing right now. 

Anyway, I noticed that plex showed a bunch of content missing. I restarted rclone-rd, and still missing a lot. Logged into DMM and almost everything was gone. Thank goodness i had a json hash backup. I used the restore and eventually rclone-rd had everything back, however zurg did not. It was still stuck at the very same small list of items left that DMM/Plex had before I restored. 

I restarted Zurg and all the items showed up again on zurg:port/http/

**Comment by JurajNyiri** [comment] 2023-12-08 12:56
I confirm the bug in the latest hotfix.3.

When I add multiple new downloads at the same time, zurg only reloads one and fails to reload the rest of them, this is resolved by a restart.

**Comment by Pukabyte** [comment] 2023-12-08 23:21
This is a duplicate issue of #10

**Comment by kennyparsons** [comment] 2023-12-08 23:34
While the outcome seems similar, I'm also seeing multiple issues where zurg appears ultra aggressive on removing torrents. Re-adding them via DMM shows the file is still available. I had to turn off this feature for now.

**Comment by yowmamasita** [comment] 2023-12-09 00:04
@kennyparsons what exactly do you see in the logs?

If it's `Removing torrent %s from zurg database` it doesn't actually delete the torrent

**Comment by yowmamasita** [comment] 2023-12-09 00:04
Update: I have a new update that's currently building now to resolve this issue

**Comment by yowmamasita** [comment] 2023-12-09 00:05
Duplicate of #10 I'll update there once it's built

**Closed by yowmamasita** 2023-12-09 00:05 UTC

**Comment by kennyparsons** [comment] 2023-12-09 00:08
> @kennyparsons what exactly do you see in the logs?
> 
> 
> 
> If it's `Removing torrent %s from zurg database` it doesn't actually delete the torrent

So I was just running interactively so I don't have logs (I did not capture the output). 

But I can say something deleted about 100 downloads, which I had to restore with DMM json hash backup.

**Comment by yowmamasita** [comment] 2023-12-09 00:10
@kennyparsons please create a new issue once you have logs, I'd be happy to look into it
